version: '3.1'
services:
  nginx:
    container_name: nginx
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    depends_on:
      - node
    environment:
      - "HOSTNAME=api:3000"
    ports:
      - "3000:3000"
  node:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    container_name: "nodejs"
    environment:
      - "NODE_ENV=production"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
    container_name: redis
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: jaimelespates
      POSTGRES_DB: db
      PGDATA: /data/postgres
